### PR TITLE
InfluxDB >=0.9 support

### LINKED ISSUE #41: circular import when import graphite_api
\>>>import graphite_influxdb

Traceback (most recent call last):
  File "graphite_api/app.py", line 63, in <module>
    configure(app)
  File "graphite_api/config.py", line 127, in configure
    finders.append(load_by_path(finder)(config))
  File "graphite_api/config.py", line 74, in load_by_path
    return getattr(finder, klass)
AttributeError: 'module' object has no attribute 'InfluxdbFinder'

### LINKED ISSUE #43: support for influxdb 0.9
Does this work with influxdb 0.9?

### PR DESCRIPTION
**Pull request by pkittenis**
This PR adds InfluxDB >= 0.9 support. InfluxDB <= 0.8.x is *no longer supported*.

List of changes:
 * Support InfluxDB ``>=0.9``. ``>=0.9.2`` highly recommended due to bug causing DB crash on group by queries. Fixes #43 
 * Removed any and all attempts to import from ``graphite_api.app`` which were causing cyclical dependencies. Fixes #41 
 * Removed cache support which never worked ( see #41 ). Cache support is in graphite-api webapp and is used for all requests hitting graphite-api if enabled.
 * Added travis-ci configuration file for automated testing
 * Unit tests and InfluxDB integration tests (!) for new or changed code. [~78% code test coverage on this branch.](https://travis-ci.org/pkittenis/graphite-influxdb/jobs/73033582)
 * `Statsd` client generated if `statsd` is configured rather than imported from ``graphite_api.app`` ( #41 )
 * Removed `fix_datapoints*` functions as they are now unnecessary due to `group by` in InfluxDB queries.
 * Added `requirements.txt` file for required influxdb library version and graphite-api.

Grafana talking to Graphite-API with graphite-influxdb plugin and InfluxDB 0.9.2:

grafana_graphite_influxdb_0 9 2

### CODE REVIEW

**Comment by Dieterbe** [comment]
> InfluxDB <= 0.8.x is no longer supported.

why? there's still a bunch of people on 0.8
can't we support both and have a flag to decide which code to use?

> Removed cache support which never worked

heh? pretty sure the cache used to work fine for me.

> Removed fix_datapoints* functions as they are now unnecessary due to group by in InfluxDB queries.

did you mean fill? are you sure all corner cases are covered? (i.e. see notes throughout fix_datapoints)

**Comment by pkittenis** [comment]
Yes, regarding 0.8, unfortunately there is no good way to do that that I can see. The API is different, the QL is different the cient and client endpoints are different, the data returned is different and needs different processing and so on.

I would suggest making a new major version of graphite-influxdb for supporting influxdb >= 0.9 and leaving ``0.4`` for InfluxDB <= 0.8 support. `0.4` versions of graphite-influxdb will continue to work with influxdb <= 0.8 as before.

The cache works on the webapp level - just not within `graphite_influxdb` :). The `_CACHE` object was always set to `NullCache` even with cache configured for me due to the cyclical import. Feel free to re-test.

> did you mean fill? are you sure all corner cases are covered? (i.e. see notes throughout fix_datapoints)

Group by automatically uses fill in influxdb's queries. 

There are [integration tests for the the new behaviour](https://github.com/pkittenis/graphite-influxdb/blob/influxdb_upgrade/tests/test_influxdb_integration.py#L105) which should cover corner cases - feel free to review them. If there's something missing let me know and can write a test for it.

Have also tested manually with Grafana and Grafana's graphs talking directly to influxdb are identical to graphs from graphite-api/graphite-influxdb. Grafana also uses group by for its influxdb queries.

**Comment by Dieterbe** [comment]
> Yes, regarding 0.8, unfortunately there is no good way to do that that I can see. The API is different, the QL is different the cient and client endpoints are different, the data returned is different and needs different processing and so on.

so? does that prevent us from supporting both at once? it's OK to use different code paths and different clients. we could split it up in 2 modules for example.

> I would suggest making a new major version of graphite-influxdb for supporting influxdb >= 0.9 and leaving 0.4 for InfluxDB <= 0.8 support. 0.4 versions of graphite-influxdb will continue to work with influxdb <= 0.8 as before.

and maintain 2 branches? i'm not against it, it just seems like more work.

**Comment by pkittenis** [comment]
Yes, split it into 2 modules would certainly work if you'd rather do that. I was not suggesting maintaining different branches but leaving `0.4.x` release as it is. Up to you. 

Not likely I'll have the bandwidth to make that kind of change at the moment unfortunately. 

Two modules, the `0.8` compatible `graphite_influxdb.py` from master branch and this one for `0.9` with a configuration switch to choose which to import should be pretty quick to do though.

**Comment by pkittenis** [comment]
Regarding cache - I suspect you are running with `graphite-web` and therefor not hitting the `graphite-api` circular import.

With `graphite-api` the cache in graphite_influxdb never worked due to circular import. On master branch:

```python
In [2]: import graphite_influxdb
{"path": "/etc/graphite-api.yaml", "event": "loading configuration"}
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-6ee93133cf6a> in <module>()
----> 1 import graphite_influxdb

graphite-influxdb/graphite_influxdb.py in <module>()
     52 _CACHE = None
     53 try:
---> 54     from graphite_api.app import app
     55 except ImportError:
     56     try:

graphite-influxdb/env/local/lib/python2.7/site-packages/graphite_api/app.py in <module>()
     46 
     47 app = Graphite(__name__)
---> 48 configure(app)
     49 
     50 methods = ('GET', 'POST')

graphite-influxdb/env/local/lib/python2.7/site-packages/graphite_api/config.pyc in configure(app)
     94     finders = []
     95     for finder in config['finders']:
---> 96         finders.append(load_by_path(finder)(config))
     97     loaded_config['store'] = Store(finders)
     98     loaded_config['searcher'] = IndexSearcher(config['search_index'])

graphite-influxdb/env/local/lib/python2.7/site-packages/graphite_api/config.pyc in load_by_path(path)
     68     module, klass = path.rsplit('.', 1)
     69     finder = import_module(module)
---> 70     return getattr(finder, klass)
     71 
     72 

AttributeError: 'module' object has no attribute 'InfluxdbFinder'
```
Even if circular import is handled, all the code can ever do is set `_CACHE` to `NullCache()`.

Regardless, cache is applied at the webapp level, ie a `GET /metrics/find<..> ` with cache enabled at `graphite-api.yaml` will get cached by flask without any cache specific code in `graphite_influxdb`. 

In the case of django, the same would apply if cache is enabled at `MIDDLEWARE_CLASSES` configuration setting, ie cache enabled at site level.

As mentioned before, it is not possible to import from `graphite_api.app` without causing circular import error - also the reason why statsd attempted import was removed.

**Comment by Dieterbe** [comment]
i'm sorry for the slow reaction, let me know what else i can do to make your use of this project more comfortable.

**Comment by pkittenis** [comment]
No problem at all - thank you for the merge and the excellent project :)

**Comment by juise** [comment]
It's awesome! Looking forward to try migrate from influx 0.8 to 0.9 with new graphite-influxdb driver.

If I understood correctly the file cache doesn't support any more? If I use graphite-api should I use this graphite-influxdb driver instead Dieterbe's GitHub version?

**Comment by pkittenis** [comment]
@juise  - cache never worked under graphite-api, see details above. Under graphite-web/django cache will work if enabled at `MIDDLEWARE_CLASSES` configuration setting.

Cache is on the webapp, graphite-influxdb is a plugin to the webapp. Anything the webapp uses the plugin will use.

You can also use an HTTP cache in front of the webapp for more control, eg varnish.

**Comment by juise** [comment]
Ok, got it! How about publish new version into pip repo?

**Comment by pkittenis** [comment]
New version released to pip would be up to @Dieterbe :)

**Comment by Dieterbe** [comment]
what are the commands again? i always forget
